version: '3'
services:
  nginx:
    image: "nginx:alpine"
    restart: always
    ports:
      - 8080:80
    volumes:
      - .:/bot
      - ./nginx/default.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
  php:
    build: app
    restart: always
    volumes:
      - .:/bot
    depends_on:
      - mysql
  mysql:
    image: "mysql:5.7"
    restart: always
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
      - ./structure.sql:/docker-entrypoint-initdb.d/structure.sql
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
